### ISSUE TITLE
NotADirectoryError on Windows

### ISSUE THREAD

**Issue by Carlangelomikhael** [medkit-lib/medkit#27]
The provided example for fine-tuning a BERT Model results in this error:

2024-02-26 12:47:02,763 - DefaultPrinterCallback - INFO - Saving checkpoint in checkpoints\checkpoint_001_26-02-2024_12:47
Traceback (most recent call last): history = trainer.train()
NotADirectoryError: [WinError 267] The directory name is invalid: 'checkpoints\\checkpoint_001_26-02-2024_12:47'

**Comment by ghisvail** [comment]
Hi, which versions of `medkit` are you using? Version 0.13.1 features a fix for Windows paths.

**Comment by Carlangelomikhael** [comment]
Hello, I am using 0.13.0. I will update it right now. Thank you for your
prompt response.
